source 'https://github.com/CocoaPods/Specs.git'

install! 'cocoapods', :preserve_pod_file_structure => true

platform :ios, '9.0'
inhibit_all_warnings!

workspace 'IGWebLogger.xcworkspace'

target 'IGWebLoggerExample' do
  pod "IGWebLogger", :path => '../'
end
